language: c

cache:
  apt: true
  directories:
    - .cache

env:
  matrix:
    - TEST_BASH_VERSION='default-travis'
    - TEST_BASH_VERSION='4.3'
    # - TEST_BASH_VERSION='4.2'
    # - TEST_BASH_VERSION='4.1'
    # - TEST_BASH_VERSION='4.0'
    # - TEST_BASH_VERSION='3.3'
    # - TEST_BASH_VERSION='3.2'
    # - TEST_BASH_VERSION='3.1'
    # - TEST_BASH_VERSION='3.0'

before_install:
  - git clone https://github.com/sstephenson/bats.git .cache/bats || (cd .cache/bats && git pull)
  # - ./misc/build_bash.sh .cache .tmp 2.05b
  # - ./misc/build_bash.sh .cache .tmp 3.0 3.1 3.2 3.3 4.0 4.1 4.2 4.3
  - ./misc/build_bash.sh .cache .tmp 4.3
  - ls -al .cache/

before_script:
  - PATH="$PWD/.cache/bats/bin:$PWD/.cache/bash-$TEST_BASH_VERSION/bin:/usr/local/bin:/bin:/usr/bin"

script:
  - echo $BASH_VERSION
  - bats --tap test

notifications:
  email:
    on_success: never
